production:
  adapter: mysql
  database: vreg
  username: root
  password: masula
  host: localhost

bart2:
  adapter: mysql
  database: bart2_development
  username: root
  password: masula
  host: 127.0.0.1

development:
  adapter: mysql
  database: vreg
  username: root
  password: masula
  host: localhost

test: &TEST
  adapter: mysql
  database: vreg
  username: root
  password: masula
  host: localhost

cucumber:
  <<: *TEST

migration:
  adapter: mysql
  database: vreg
  username: root
  password: masula
  host: localhost

