# production:
#   adapter: mysql
#   database: openmrs
#   username: root
#   password:
#   host: localhost

bart2:
  adapter: mysql
  database: bart2_development
  username: root
  password: masula
  host: 127.0.0.1

development:
  adapter: mysql
  database: vreg
  username: root
  password: masula
  host: localhost

test: &TEST
  adapter: mysql
  database: bart2_test
  username: root
  password: password
  host: localhost

cucumber:
  <<: *TEST

migration:
  adapter: mysql
  database: test
  username: root
  password: password
  host: localhost

